In [14]:
'''
Read the msm and msw data set and print the modified datasets containing the relative abundance
'''

import pandas as pd


msm = pd.read_csv('MSM43.csv')
msw = pd.read_csv('msw43.csv')

feature_list = ['d5__lactobacillus','d5__corynebacterium1','d5__gardnerella','d5__sneathia','d5__finegoldia','d5__anaerococcus','d5__peptoniphilus','d5__staphylococcus','d5__streptococcus',
            'd5__veillonella','Other']

msm = msm[feature_list]
msw = msw[feature_list]

,d5__lactobacillus,d5__corynebacterium1,d5__gardnerella,d5__sneathia,d5__finegoldia,d5__anaerococcus,d5__peptoniphilus,d5__staphylococcus,d5__streptococcus,d5__veillonella,Other
0,7,26358,22537,12,146,343,289,9379,30,10,7085
1,12,63503,10,12,42,35,29,18231,29,6,2071
2,4,2106,6,7,66,462,56,1349,55673,5,6821
3,15,2479,40810,6304,97,256,88,2786,31,21960,7965
4,4,9982,105,26028,217,21735,187,363,6012,7172,3468
5,4,13650,8602,28609,152,617,0,1196,4,8166,6042
6,33,8105,10042,25609,280,6988,144,1284,170,5972,17855
7,1099,12433,7210,531,3369,10995,4836,913,8443,6917,24776
8,1,34341,0,0,127,945,26,831,9014,0,13438
9,2515,1856,981,1,5081,1628,2719,567,1714,31,11732
10,8963,4815,2048,0,80,260,11,916,1476,0,5433
11,43769,15704,3502,2185,2406,4263,886,16155,5092,496,15539
12,9575,5058,3024,6510,1360,997,753,1383,1005,432,4514
13,12955,8374,2686,1488,1582,1288,433,1531,999,624,7084
14,4126,3887,3434,3716,231,1295,781,1696,840,417,14386
15,3552,2712,6159,3105,455,2246,3348,527,1095,285,12500
16,5954,2822,2876,1033,359,2808,226,1131,4258,155,5487
17,2979,1711,9870,817,315,2799,231,5183,586,91,3505
18,5845,2276,6865,2681,434,424,200,898,379,120,4868
19,9,26504,13,6,3969,16755,5954,2171,1522,3050,4214
20,44,522,3939,19099,10096,10992,8126,44,966,6454,25745
21,20,25654,799,10,892,1584,528,1232,27415,9,3876
22,2815,14939,7,5,16,825,198,6060,559,3,3380
23,25,34755,3,18,1277,1460,1148,16739,223,21,20180
24,1,1958,31455,3236,1033,1156,80,135,11571,20482,3555
25,0,21054,0,0,196,1596,34,5766,1,0,1636
26,3,44289,1,1,1235,6851,576,8391,3,0,7128
27,20306,7982,0,1,5620,11651,3356,5371,309,1,7805
28,1956,7368,10,1,142,518,232,1499,418,25,33876
29,0,14718,0,0,72,680,6,2245,25818,0,5702
30,30220,2556,5197,8175,1042,3860,923,65,79,22021,8812
31,24258,17273,3025,3432,945,8983,1433,13353,876,3741,13133
32,1873,1772,3282,1598,197,672,3597,2384,429,206,11401
33,2227,12528,334,0,3170,4168,903,454,560,278,7238
34,69,1269,1448,8001,4774,10671,3568,1771,82,840,4160
35,162,85,2682,60,1387,2672,2207,12,31,9,11459
36,9852,6936,5714,7901,569,12170,7275,1271,3111,580,32864
37,4146,3155,1339,11049,18289,480,247,993,537,106,2990
38,13097,3736,1864,1859,936,430,418,802,1430,142,5043
39,11481,2572,2470,767,353,3830,201,2429,538,246,2648
40,11890,27075,7234,5215,702,2631,1759,1399,2062,817,14513
41,27079,23665,7418,12568,3981,835,893,3434,1669,297,6186
42,8129,3057,2670,773,1047,3597,424,6744,1859,212,6033

In [11]:
## calculate the relative abundance of each taxa and map to a csv file.
## msm

for i in range(43):
    total1 = msm.loc[i,:].sum()
    for j in range(11):
            msm.iloc[i,j] = msm.iloc[i,j]/total1
            

msm.to_csv('msm_tt_rel_abundance.csv')

In [17]:
# msw

## calculate the relative abundance of each taxa and map to a csv file.
## msm

for i in range(43):
    total2 = msw.loc[i,:].sum()
    for j in range(11):
            msw.iloc[i,j] = msw.iloc[i,j]/total2
#msw
msw.to_csv('msw_tt_rel_abundance.csv')